'use strict';

exports = module.exports = {
  businessName: 'Flowers Unlimited, Inc.',
  city: 'Saint Petersburg',
  street1: '5532 66th Street North',
  street2: '',
  state: 'FL',
  postal: '33709',
  country: 'US',
  website: 'http://www.order-flowers-petersburg-florist.com/',
  hours: '',
  hide: '',
  phone: '(727) 384-5900',
  fax: '',
  email: '',
  owner: '',
  isActive: '',
  isDeleted: '',
  clientId: '',
  legacyClient: '',
  LAT: '',
  LON: '',
  agency: '',
  category: '',
  categories: '',
  keywords: '',
  socials: '',
  competitors: '',
  reportingLists: '',
  links: '',
  submissions: '',
  custom1: '',
  custom2: '',
  custom3: '',
  custom4: '',
  custom5: '',
  status: '',
  tokenGoogle: ''
};
