'use strict';

exports = module.exports = {
  'id': 1686509,
  'suite': null,
  'deleted': 'false',
  'LAT': 44.260289,
  'LON': -88.233114,
  'status': 'Paused',
  'country': 'US',
  'orders': 2,
  'name': 'Heart Of The Valley Chem-Dry',
  'owner': 'Tom Pennings',
  'partnerUsername': 'HIBUTEST@lssdev.com',
  'street': '2205 Kavanaugh Rd',
  'hours': 'Monday: 8am to 5pm  \nTuesday: 8am to 5pm |  \nWednesday: 8am to 5pm |  \nThursday: 8am to 5pm |  \nFriday: 8am to 5pm |  \nSaturday: Closed\nSunday: Closed\nCall for appointment',
  'city': 'Kaukauna',
  'state': 'WI',
  'zipcode': '54130',
  'phone': '(920) 766-2992',
  'fax': '',
  'website': '',
  'email': 'tpennings1@new.rr.com',
  'facebook': 'No Customer FB provided',
  'twitter': 'No Customer Twitter provided',
  'linkedin': '',
  'years': '2006',
  'description': '',
  'payment': 'Check, Cash',
  'services': 'Residential Upholstery , Commercial Upholstery, Commercial carpet, Upholstery cleaning, In-home consultations',
  'license': '',
  'keyword1': 'Upholstery shop',
  'keyword2': '',
  'keyword3': '',
  'keyword4': '',
  'keyword5': '',
  'keyword1_location': '',
  'keyword2_location': '',
  'keyword3_location': '',
  'keyword4_location': '',
  'keyword5_location': '',
  'notes': 'sales-rep-name: Charley Bergs \nsales-rep-email: charley.bergs@hibu.com\ncontact-name: Tom Pennings\ncontact-email: tpennings1@new.rr.com\ncontactphone: 920-858-7188\naddress-and-service-radius: Kaukauna, WI, USA - 35mi | \nlanguages: English\ncategory: Upholstery Shop\nbusiness-description-short: Heart Of The Valley Chem-Dry provides residential and commercial carpet and upholstery cleaning and in-home consultations to the Kankauna and surrounding areas. \nvideo-link: No Customer Video Provided\ncall_for_appt: true',
  'hide': 'false',
  'isInactive': true,
  'createdAt': '2016-01-20T13:11:26.000Z',
  'deletedAt': null,
  'inactiveAt': null,
  'custom1': 'JBMTS8ZZW',
  'custom2': 'WAVS',
  'custom3': '659976',
  'custom4': '3090860',
  'custom5': '',
  'publicKey': 'bfc4a7ae54a18b7f615f671943d6c33e',
  'tokenGoogle': null,
  'categoryGoogle': '',
  'partner': 10041
};
